---

internal_interface: "eth1" 
int_net_addr: "10.0.0.0"
int_ip_addr: "10.1.1.3"
int_net_mask: "255.0.0.0"
int_gateway: "10.1.1.4"

external_interface: "eth0"
ext_ip_addr: "86.50.166.64"
ext_net_mask: "255.255.255.0"
ext_gateway: "86.50.166.1"
ext_net_addr: "86.50.166.0"

internal_ip: "{{int_ip_addr}}"
internal_net: "10.0.0.0/8"

network_ether_interfaces:
  - device: "{{external_interface}}"
    bootproto: "static"
    onboot: "yes"
    address: "{{ext_ip_addr}}"
    netmask: "{{ext_net_mask}}"
    gateway: "{{ext_gateway}}"
    defroute: "yes"
    nm_controlled: "no"
    type: "Ethernet"
    route:
      - network: "{{ext_net_addr}}"
        netmask: "{{ext_net_mask}}"
        gateway: "{{ext_gateway}}"

  - device: "{{internal_interface}}"
    bootproto: "static"
    onboot: "yes"
    address: "{{int_ip_addr}}"
    netmask: "{{int_net_mask}}"
    nm_controlled: "no"
    type: "Ethernet"

vcpus: "{{vm_cpus}}"
ram: "{{vm_mem}}"
disks:
  - { path: "/var/vms/grid.raw", size: 200 }
bridges:
  - br_ext
  - br_int
location: "{{repo_location}}"
kickstart_tempdir: "/tmp"
inventory_hostname: "grid"
fqdn: "{{siteName}}-grid.{{siteDomain}}"
networks:
  - "network --onboot={{enable_ext_nic}} --device={{external_interface}} --bootproto=static --ip={{ext_ip_addr}} --netmask={{ext_net_mask}} --nameserver={{nameserver1}} --hostname={{ fqdn }} --gateway={{ext_gateway}} --noipv6"
  - "network --onboot={{enable_int_nic}} --device={{internal_interface}} --bootproto=static --ip={{int_ip_addr}} --netmask={{int_net_mask}} --nodefroute --noipv6"
root_password: "{{ lookup('password', 'credentials/'+ inventory_hostname  +'_rootpw length=15') }}"

# Slurm
slurm_type: "submit"

# Ferm - firewall
ferm_rules_extra:
 10_nat:
 - chain: FORWARD
   table: filter
   domains: [ip, ip6]
   rules:
     - {rule: "interface {{ internal_interface }} outerface {{ external_interface }} mod state state (ESTABLISHED RELATED) mod comment comment 'forward establish and related' ACCEPT;", comment: "forwarding"}
     - {rule: "interface {{ internal_interface }} outerface {{ external_interface }} mod state state (ESTABLISHED RELATED) mod comment comment 'forward from internal net' ACCEPT;", comment: "forwarding"}
 - chain: POSTROUTING
   table: nat
   domains: [ip]
   rules:
     - {rule: "daddr ( {{ trusted_public_networks }} {{ internal_net }} ) mod comment comment 'masquerade for internal net' ACCEPT;", comment: "masquerade"}
     - {rule: "outerface br_ext saddr ( {{ internal_net }} ) mod comment comment 'masquerade for internal net' MASQUERADE;", comment: "masquerade"}

#NTP
ntp_config_server: [ "{{ hostvars[groups['install'][0]]['ansible_hostname'] }}", "{{ hostvars[groups['admin'][0]]['ansible_hostname'] }}" ]

#CVMFS
cvmfs_http_proxy: "{{ http_proxy }}"
cvmfs_quota_limit: "10240"

# Do not extra install infiniband packages
infiniband_available: False

# NFS mounts

nfs_mount: |
  10.2.1.5:/scratch /scratch                nfs4 defaults 0 0
  10.2.1.5:/home    /home                   nfs4 defaults 0 0

# ARC Frontend vars
