---
language: python
python: "2.7"
sudo: required

env:
  #matrix:
  - OS_TYPE=centos OS_VERSION=7 ANSIBLE_VERSION=1.9.2

branches:
  only:
#  - master
  - travis

services:
  - docker

before_install:
  - sudo apt-get update
#  - sudo apt-get upgrade lxc-docker
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - docker pull weldpua2008/docker-ansible:${OS_TYPE}${OS_VERSION}_v${ANSIBLE_VERSION}
#  - sudo apt-get update -qq
#  - sudo apt-get install tree

install:
  # Install Ansible.
  #- pip install ansible

  # /home/travis/build/CSC-IT-Center-for-Science/fgci-ansible/tests/roles/ansible-role-aliases or /home/travis/build/CSC-IT-Center-for-Science/fgci-ansible/tests/ansible-role-aliases or /home/travis/build/CSC-IT-Center-for-Science/ansible-role-aliases
  # roles_path = /opt/mysite/roles:/opt/othersite/roles
  #
  # Add ansible.cfg to pick up roles path.
  #- "{ echo '[defaults]'; echo 'roles_path = ../:fgci-ansible/roles:roles'; } >> ansible.cfg"
  ## Add an empty ssh.config which is called from ansible.cfg
  #- "echo '' >> ssh.config"
  ## Print ansible version
  #- "ansible --version"

script:
  # Install all the required roles.
  #- "ansible-galaxy install -r requirements.yml --force"
  ## Where are we?
  - "find $PWD"

  ## Syntax Check
  #- "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"

  ## --check would be nice, but the current travis config is Ubuntu only. Would need to use Travis's docker to run with CentOS7
  ##- "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo --check"

 ## Run the role/playbook with ansible-playbook.
  #- "ansible-playbook -i tests/inventory tests/test.yml --connection=local --sudo"
  # Run the test in Container
  #- docker run --rm=true -v `pwd`:/fgci-ansible:rw weldpua2008/docker-ansible:${OS_TYPE}${OS_VERSION}_v${ANSIBLE_VERSION} /bin/ls /
  #- docker run --rm=true -v `pwd`:/fgci-ansible:rw weldpua2008/docker-ansible:${OS_TYPE}${OS_VERSION}_v${ANSIBLE_VERSION} /bin/bash -c "/fgci-ansible/tests/test-in-docker-image.sh ${OS_TYPE} ${OS_VERSION} ${ANSIBLE_VERSION}"
  - docker run --rm=true -v `pwd`:/fgci-ansible:rw centos:7 /bin/bash -c "/fgci-ansible/tests/test-in-docker-image.sh ${OS_TYPE} ${OS_VERSION} ${ANSIBLE_VERSION}"

notifications:
  email: false
  flowdock:
    secure: "lxqZTTUCUYy19JzwXnH/kRcndYwNasUYpa0AK0vcRqTRSoULRzwE2jcJUk2YBz0qTBcTgAkinj1VQbImdrl68NTPDTmOZM4+hPZ8RQNTGR7VJwy4Ynjl/RtvxmwvoW/kSZJI3twDvPpAl2yEKfiPwSE4kYNFs84w43WieNhX3qO0LN9EdFykV6M0xeZgGc71v6oGof3n9HhBMfMUYU6YZJKvirHJNwAxHsWiFSq+dfDA5hqDyilwuQM0toNgjsFi6F7b40vOVJPGJKdSNekrFgp2Gm/Fzd83sO/Sp1ord9v73UflshejKuK2/iMRddPW5JDl05FNrJ7x6xcCfK9sxOj5KDELotagHCDdCTqX4USelBpI7DeO9yV8NAIxyL2KAFi5b3uwvF5reitGhRfdeqA0B9eK+k6vdRQ/xKryYc48hVX46wraL2ibZv2gbic7vpYdxiWFUirKB9NBoQu7JHkTT/LT3LjbC9/uL9c4qRyakAnQwhgi4/sEk7f9euvtZA6MJfZpCzfiYVt3rGe6H9HqcCflnxW5F1ZjLBSkHk02rNn6hcfFxGHSS5x1362F9JCwVkAWgJ43JvQLRxobW4htbx56+niX0zS+vs2kK5K3NxUCJzInUb4UV5/9lwcCBZQJL0fD4u2Gy8/TC7MrhhOVxkSSPmjjoonaRPY497c="
