---
- name: First add users to admin node as root
  hosts: admin
  remote_user: root

  roles: 
  - { role: ansible-role-users, tags: [ 'users', 'admin-users', 'user' ] }

- name:  Configure Admin Node
  hosts: admin
  sudo: yes

  roles:
  - { role: ansible-role-yum, tags: [ 'yum', 'repos' ] }
  - { role: network_interface, tags: [ 'network' ],
    when: internal_interface in ansible_interfaces and
          external_interface in ansible_interfaces }
  - { role: ip_forwarder, tags: [ 'network' ],
    when: internal_interface is defined and
          external_interface is defined and
          internal_net is defined and
          internal_interface in ansible_interfaces and
          external_interface in ansible_interfaces }
  - { role: ansible-role-ferm-firewall, tags: [ 'firewall' ] }
  - { role: ansible-role-ntp, tags: [ 'ntp' ] }
  - { role: ansible-role-yum-cron, tags: [ 'yumcron' ] }
  - { role: ansible-role-rsyslog, tags: [ 'rsyslog' ] }
  - { role: ansible-role-aliases, tags: [ 'aliases', 'email' ] }
  - { role: ansible-role-sshd, tags: [ 'sshd', 'ssh' ] }
  - { role: ansible-role-smartd, tags: [ 'smartd' ] }
  - { role: ansible-role-dell, tags: [ 'dell' ] }
  - { role: ansible-role-rdma, tags: [ 'rdma', 'infiniband' ] }
  - { role: ansible-role-flowdock, tags: [ 'flowdock' ] }
