---
- name: Compute Nodes
  hosts: compute
  remote_user: root

  roles: 
  - { role: network_interface, tags: [ 'network' ] }
  - { role: ip_forwarder, tags: [ 'network' ], 
    when: internal_interface is defined and
          external_interface is defined and
          internal_net is defined and
          internal_interface in ansible_interfaces and
          external_interface in ansible_interfaces }
  - { role: dns, tags: [ 'dns' ] }
  - { role: ansible-role-ntp, tags: [ 'ntp' ] }
  - { role: ansible-role-yum-cron, tags: [ 'yumcron' ] }
  - { role: ansible-role-rsyslog-client, tags: [ 'rsyslog-client' ] }
  - { role: ansible-role-slurm, tags: [ 'slurm' ] }
  - { role: ansible-role-cvmfs, tags: [ 'cvmfs' ] }
