---

# This is used with ansible-pull
# The compute group here is the one defined in fgci-ansible/localhosts file
# _Not_ the one in fgci-ansible/hosts
#
- hosts: compute
  remote_user: root

  vars:

    workdir: /var/lib/ansible/local
    logfile: /var/log/ansible-pull.log
    cron_user: root
    schedule: '*/15 * * * *'
    repo_url: https://github.com/CSC-IT-Center-for-Science/fgci-ansible.git

    ntp_config_server: [ "10.1.1.2", "10.1.1.1" ]

  pre_tasks:
      
    - name: get variables files
      get_url: url="http://10.1.1.2/pull_variables.yml" dest=/root mode=0640 owner=root group=admin

    - name: include variables
      include_vars: /root/pull_variables.yml

    - name: Install ansible
      yum: pkg=ansible state=installed

    - name: Create local directory to work from
      file: path={{workdir}} state=directory owner=root group=root mode=0751

     # grab files we don't want in the main github:
     #  - the hosts file
     #    - IP addr
     #  - the munge key
     # get some variables:
     #  - facts from the install node 
     #    - hostname, ip address
     #  - adminMailAddr
     #  - root_keys


  roles: 
  - { role: ansible-role-yum, tags: [ 'yum', 'repos', 'login' ] }
#  - { role: network_interface, tags: [ 'network' ] }
  - { role: ansible-role-ntp, tags: [ 'ntp' ] }
  - { role: ansible-role-nis, tags: [ 'nis' ] }
  - { role: ansible-role-yum-cron, tags: [ 'yumcron' ] }
  - { role: ansible-role-rsyslog, tags: [ 'rsyslog' ] }
  - { role: ansible-role-aliases, tags: [ 'aliases', 'email' ] }
  - { role: ansible-role-nhc, tags: [ 'nhc', 'slurm' ] }
  - { role: ansible-role-slurm, tags: [ 'slurm' ] }
  - { role: ansible-role-cvmfs, tags: [ 'cvmfs' ] }
  - { role: ansible-role-rdma, tags: [ 'rdma', 'infiniband' ] }
  - { role: ansible-role-system-limits, tags: [ 'limits', 'limit' ] }
  - { role: ansible-role-nfs_mount, tags: [ 'nfsmount' ] }
  - { role: ansible-role-arc-client, tags: [ 'arc', 'nordugrid' ] }
  - { role: ansible-role-fgci-bash, tags: [ 'bash'] }
  - { role: ansible-role-collectd, tags: [ 'collectd', 'monitoring' ] }
#  - { role: ansible-role-flowdock, tags: [ 'flowdock' ] }
  - { role: ansible-role-cuda, tags: [ 'cuda', 'nvidia' ] }

