---
#
# This role will reboot all compute nodes
#

- name: Reboot Compute Nodes
  hosts: compute
  remote_user: root
  gather_facts: false 
  
  tasks:
  - name: Reboot compute nodes
    command: /sbin/shutdown -r
    ignore_errors: yes
