---
#
# This role will reboot all compute nodes
#

- name: Reboot Compute Nodes
  hosts: compute
  remote_user: root
  
  tasks:
  - name: Reboot compute nodes
    command: /sbin/reboot
    ignore_errors: yes
