---
- src: https://github.com/resmo/ansible-role-ntp
  path: roles
  version: 0.4.0

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-fgci-admin
  path: roles

- src: https://github.com/kaffeeh/ansible-yum-cron
  path: roles
  name: ansible-role-yum-cron
  version: fef55b2adcc2062d2727f1d06886f0abedd3907f

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-users
  path: roles

- src: https://github.com/CSC-IT-Center-for-Science/ansible-role-rsyslog-client
  path: roles
