# ansible-playbook file: site.yml
#


- name: Apply common configuration to all hosts  
  hosts: all
  remote_user: root

  roles:
    - common

- name: Boot Server
  hosts: boot
  remote_user: root

  roles:
    - boot
