# ansible-playbook file: site.yml
#

- name: Apply common configuration to all hosts  
  hosts: all
  remote_user: root

  roles:

# admin.yml installs the admin node
- include: admin.yml


# install.yml installs the install node
- include: install.yml

- name: Compute Node
  hosts: compute
  remote_user: root

  roles:

