# ansible-playbook file: site.yml
#

#- name: Apply common configuration to all hosts  
#  hosts: all
#  remote_user: root
#
#  roles:

###
# after_provisioning.yml installs the admin node
- include: admin.yml
- include: install.yml
- include: login.yml
- include: grid.yml
- include: after_provisioning.yml

#- name: Compute Node
#  hosts: compute
#  remote_user: root
#
#  roles:
