---
internal_interface: "eth1" 
external_interface: "eth0"
internal_net: "10.1.0.0/16"
int_ip_addr: "10.1.1.4"
internal_ip: "{{int_ip_addr}}"
int_net_mask: "255.255.0.0"
ext_ip_addr: "193.166.3.188"
ext_net_mask: "255.255.255.128"
vcpus: "{{vm_cpus}}"
ram: "{{vm_mem}}"
disks:
  - { path: "/var/vms/login.raw", size: 12 }
bridges:
  - br_ext
  - br_int
location: "{{repo_location}}"
kickstart_tempdir: "/tmp"
inventory_hostname: "login"
fqdn: "{{siteName}}-login.{{siteDomain}}"
networks:
  - "network --onboot={{enable_ext_nic}} --device={{external_interface}} --bootproto=static --ip={{ext_ip_addr}} --netmask={{ext_net_mask}} --nameserver={{nameserver1}} --hostname={{ fqdn }} --gateway={{ext_gateway}} --noipv6"
#  - "network --onboot={{enable_int_nic}} --device={{internal_interface}} --bootproto=static --ip={{int_ip_addr}} --netmask={{int_net_mask}} --nodefroute --noipv6"
root_password: "{{ lookup('password', 'credentials/'+ inventory_hostname  +'_rootpw length=15') }}"

# Slurm
slurm_type: "submit"

# Ferm - firewall
ferm_rules_extra:
 nat:
 - chain: FORWARD
   table: filter
   domains: [ip, ip6]
   rules:
     - {rule: "interface {{ internal_interface }} outerface {{ external_interface }} mod state state (ESTABLISHED RELATED) mod comment comment 'forward establish and related' ACCEPT;", comment: "forwarding"}
     - {rule: "interface {{ external_interface }} outerface {{ internal_interface }} mod state state (ESTABLISHED RELATED) mod comment comment 'forward from internal net' ACCEPT;", comment: "forwarding"}
 - chain: POSTROUTING
   table: nat
   domains: [ip]
   rules:
     - {rule: "daddr ( {{ trusted_public_networks }} {{ internal_net }} ) mod comment comment 'masquerade for internal net' ACCEPT;", comment: "masquerade"}
     - {rule: "outerface {{ external_interface }} saddr ( {{ internal_net }} ) mod comment comment 'masquerade for internal net' MASQUERADE;", comment: "masquerade"}

#NTP
ntp_config_server: [ "{{ hostvars[groups['install'][0]]['ansible_hostname'] }}" ]

#CVMFS
cvmfs_http_proxy: "{{ http_proxy }}"
cvmfs_quota_limit: "10240"
