---

admingroup: "admin"

# network

external_interface: "eth0"
#external_bridge: "br_ext"
ext_net_addr: "86.50.166.0"
ext_ip_addr: "86.50.166.63"
ext_net_mask: "255.255.255.0"
ext_gateway: "86.50.166.1"

internal_interface: "eth1"
#internal_bridge: "br_int"
int_net_addr: "10.0.0.0"
int_ip_addr: "10.1.1.2"
int_net_mask: "255.0.0.0"
int_gateway: "10.1.1.4"

internal_ip: "{{int_ip_addr}}"
internal_net: "10.0.0.0/8" 

network_ether_interfaces:
  - device: "{{external_interface}}"
    bootproto: "static"
    onboot: "yes"
    address: "{{ext_ip_addr}}"
    netmask: "{{ext_net_mask}}"
    gateway: "{{ext_gateway}}"
    defroute: "yes"
    nm_controlled: "no"
    type: "Ethernet"
    route:
      - network: "{{ext_net_addr}}"
        netmask: "{{ext_net_mask}}"
        gateway: "{{ext_gateway}}"


  - device: "{{internal_interface}}"
    bootproto: "static"
    onboot: "yes"
    address: "{{int_ip_addr}}"
    netmask: "{{int_net_mask}}"
    nm_controlled: "no"
    type: "Ethernet"

## DHCP_SERVER

dhcp_interfaces: "{{ internal_interface }}"
dhcp_common_domain: "fgci.csc.fi"
dhcp_common_nameservers: "{{ int_ip_addr }}, 193.166.4.24, 193.166.4.25"
#dhcp_common_nameservers: 127.0.0.1
dhcp_common_default_lease_time: 7200
dhcp_common_max_lease_time: 14400
dhcp_common_options: []
dhcp_common_parameters:
 - include "/etc/dhcp/dhcpd.d/ipxe.conf"
 - include "/etc/dhcp/dhcpd.d/nodes.conf"
dhcp_subnets:
 - base: "{{ int_net_addr }}"
   netmask: "{{ int_net_mask }}"
   routers: "{{ int_ip_addr }}"
   interface: "{{ internal_interface }}"
   domain_nameservers: "{{ int_ip_addr }}, {{ nameserver1 }}, {{ nameserver2 }}"
   domain_name: "{{ dhcp_common_domain }}"

dhcp_tftp_server_ip: "{{ int_ip_addr }}"

# Kickstart file VM specifics

vcpus: "{{vm_cpus}}"
ram: "{{vm_mem}}"

disks:
  - { path: "/var/vms/install.raw", size: 200 }
bridges:
  - br_ext
  - br_int
location: "{{repo_location}}"
kickstart_tempdir: "/tmp"
inventory_hostname: "install"
fqdn: "{{siteName}}-install.{{siteDomain}}"
networks:
  - "network --onboot={{enable_ext_nic}} --device={{external_interface}} --bootproto=static --ip={{ext_ip_addr}} --netmask={{ext_net_mask}} --nameserver={{nameserver1}} --hostname={{ fqdn }} --gateway={{ext_gateway}} --noipv6"
#  - "network --onboot={{enable_int_nic}} --device={{internal_interface}} --bootproto=static --ip={{int_ip_addr}} --netmask={{int_net_mask}} --nodefroute --noipv6"

# Slurm
slurm_type: "service"

# SSHD
sshd:
 AllowGroups: "root admin" 

# Install extra packages
unconfigured_packages:
 - git

# For sure do not install infiniband packages on install node
infiniband_available: False

# NIS server settings
nis_server: True
nis_initialize: True
nis_enabled: True


## KS profile and server Dir
ksBootSrvDir: "/var/www/html/ks"

# NFS mounts

nfs_mount: |
  10.2.1.5:/scratch /scratch                nfs4 defaults 0 0
  10.2.1.5:/home    /home                   nfs4 defaults 0 0

