heat_template_version: 2015-10-15

description: >
  Build a single FGCI machine

parameters:
  ssh_key_name:
    description: The name of the SSH key in OpenStack to add to hosts.
    type: string
  grid_node_flavor:
    description: The flavor to use for the grid VM
    type: string
  grid_node_image:
    description: The image to use for the grid VM
    type: string
  fgci_network:
    description: The internal network to use
    type: string
  grid_node_allow_ssh_cidr:
    description: The CIDR where SSH is allowed to the grid node from.
    type: string
  grid_node_allow_grid_cidr:
    description: >
      The CIDR of the network where the Grid application should be
      accessible. Use 0.0.0.0/0 to allow access from anywhere.
    type: string
  floating_ip_pool:
    type: string
    label: Floating IP pool
    description: The pool from which floating IPs should be reserved.
    default: 'public'
  fgci_network_cidr:
    type: string
    description: The CIDR of the internal network for the instances
    default: '192.168.1.0/24'

resources:

  frontend_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      name: fgci_frontend_secgroup
      rules:
        - protocol: tcp
          remote_ip_prefix: { get_param: grid_node_allow_ssh_cidr }
          port_range_min: 22
          port_range_max: 22

  install_public_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: { get_param: floating_ip_pool }

  grid_public_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: { get_param: floating_ip_pool }

  grid_node:
    type: OS::Nova::Server
    properties:
      name: grid_node
      flavor: { get_param: grid_node_flavor }
      image: { get_param: grid_node_image }
      key_name: { get_param: ssh_key_name }
      security_groups:
        - { get_resource: frontend_secgroup }
      networks:
        - network: { get_param: fgci_network }
      metadata: { 'ansible_group': 'grid' }
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            /sbin/setenforce 0
            /bin/sed -i 's/^SELINUX=.*/SELINUX=permissive/' /etc/selinux/config
          params:
            $selinux_mode: "permissive"

  grid_floating_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: grid_public_ip }
      server_id: { get_resource: grid_node }

outputs:
  grid_node:
    description: The Grid node
    value: { get_attr: [grid_node, show] }
