---

external_interface: "em1"
ext_net_addr: "86.50.166.0"
ext_ip_addr: "86.50.166.62"
ext_net_mask: "255.255.255.0"
ext_gateway: "86.50.166.1"

internal_interface: "em2"
int_net_addr: "10.1.0.0"
int_ip_addr: "10.1.1.1"
int_net_mask: "255.255.0.0"
int_gateway: "10.1.1.4"

internal_net: "10.1.1.0/16"

network_ether_interfaces:
  - device: "{{external_interface}}"
    bootproto: "static"
    onboot: "yes"
    netmask: "{{ext_net_mask}}"
    gateway: "{{ext_gateway}}"
    defroute: "yes"
    nm_controlled: "no"
    type: "Ethernet"

  - device: "{{internal_interface}}"
    bootproto: "static"
    onboot: "yes"
    nm_controlled: "no"
    type: "Ethernet"

network_bridge_interfaces:
  - device: "br_ext"
    type: "Bridge"
    bootproto: "static"
    onboot: "yes"
    #stp: "on"
    address: "{{ext_ip_addr}}"
    netmask: "{{ext_net_mask}}"
    gateway: "{{ext_gateway}}"
    ports: ["{{external_interface}}"]
    nm_controlled: "no"
    route:
      - network: "{{ext_net_addr}}"
        netmask: "{{ext_net_mask}}"
        gateway: "{{ext_gateway}}"

  - device: "br_int"
    type: "Bridge"
    bootproto: "static"
    onboot: "yes"
    #stp: "on"
    address: "{{int_ip_addr}}"
    netmask: "{{int_net_mask}}"
    ports: ["{{internal_interface}}"]
    nm_controlled: "no"

# Ferm - firewall
ferm_rules_extra:
 hypervisor:
 - chain: FORWARD
   table: filter
   domains: [ip, ip6]
   rules:
     - {rule: "interface {{ internal_interface }} outerface {{ external_interface }} mod state state (ESTABLISHED RELATED) mod comment comment 'forward establish and related' ACCEPT;", comment: "forwarding"}
     - {rule: "interface {{ external_interface }} outerface {{ internal_interface }} mod state state (ESTABLISHED RELATED) mod comment comment 'forward from internal net' ACCEPT;", comment: "forwarding"}
 - chain: POSTROUTING
   table: nat
   domains: [ip]
   rules:
     - {rule: "daddr ( {{ trusted_public_networks }} {{ internal_net }} ) mod comment comment 'masquerade for internal net' ACCEPT;", comment: "masquerade"}
     - {rule: "outerface {{ external_interface }} saddr ( {{ internal_net }} ) mod comment comment 'masquerade for internal net' MASQUERADE;", comment: "masquerade"}
 - chain: PREROUTING
   table: nat
   domains: [ip]
   rules:
     - {rule: "saddr ( {{ trusted_public_networks }} {{ internal_net }} ) mod comment comment 'masquerade for internal net' ACCEPT;", comment: "masquerade"}
 - chain: PREROUTING
   table: mangle
   domains: [ip]
   rules:
     - {rule: "saddr ( {{ trusted_public_networks }} {{ internal_net }} ) mod comment comment 'masquerade for internal net' ACCEPT;", comment: "masquerade"}

# SSHD

sshd:
 AllowGroups: "root admin" 

# Install these package
unconfigured_packages:
 - "virt-install"
 - "qemu-kvm"
 - "vim-enhanced"
 - "yum-plugin-priorities"

# Admin node receives syslog from cluster nodes
central_log_listener: True
central_logs_directory: "/var/log/remote/servers"
central_logs_retention_days: 60
