---
internal_interface: "eth1" 
external_interface: "eth0"
internal_net: "10.1.0.0/16"
int_ip_addr: "10.1.1.3"
internal_ip: "{{int_ip_addr}}"
int_net_mask: "255.255.0.0"
ext_ip_addr: "86.50.166.64"
ext_net_mask: "255.255.255.0"
vcpus: "{{vm_cpus}}"
ram: "{{vm_mem}}"
disks:
  - { path: "/var/vms/grid.raw", size: 200 }
bridges:
   - br_ext
   - br_int
location: "{{repo_location}}"
kickstart_tempdir: "/tmp"
inventory_hostname: "grid"
fqdn: "{{siteName}}-grid.{{siteDomain}}"
networks:
  - "network --onboot={{enable_ext_nic}} --device={{external_interface}} --bootproto=static --ip={{ext_ip_addr}} --netmask={{ext_net_mask}} --nameserver={{nameserver1}} --hostname={{ fqdn }} --gateway={{ext_gateway}} --noipv6"
#  - "network --onboot={{enable_int_nic}} --device={{internal_interface}} --bootproto=static --ip={{int_ip_addr}} --netmask={{int_net_mask}} --nodefroute --noipv6"
