---
internal_interface: "eth1" 
external_interface: "eth0"
internal_net: "10.1.0.0/16"
int_ip_addr: "10.1.1.2"
internal_ip: "{{int_ip_addr}}"
int_net_mask: "255.255.0.0"
ext_ip_addr: "193.166.3.190"
ext_net_mask: "255.255.255.128"
vcpus: "{{vm_cpus}}"
ram: "{{vm_mem}}"
disks:
  - { path: "/var/vms/install.raw", size: 12 }
bridges:
  - br_ext
  - br_int
location: "{{repo_location}}"
kickstart_tempdir: "/tmp"
inventory_hostname: "install"
fqdn: "{{siteName}}-install.{{siteDomain}}"
networks:
  - "network --onboot={{enable_ext_nic}} --device={{external_interface}} --bootproto=static --ip={{ext_ip_addr}} --netmask={{ext_net_mask}} --gateway={{ext_gateway}} --nameserver={{nameserver1}} --hostname={{ fqdn }}"
  - "network --onboot={{enable_int_nic}} --device={{internal_interface}} --bootproto=static --ip={{int_ip_addr}} --netmask={{int_net_mask}} --nodefroute"
root_password: "{{ lookup('password', 'credentials/'+ inventory_hostname  +'_rootpw length=15') }}"
