---
internal_interface: "em2" 
external_interface: "em1"
internal_net: "10.1.0.0/16"
int_ip_addr: "10.1.1.4"
internal_ip: "{{int_ip_addr}}"
int_net_mask: "255.255.0.0"
ext_ip_addr: "86.50.166.61"
ext_net_mask: "255.255.255.0"
vcpus: "{{vm_cpus}}"
ram: "{{vm_mem}}"
disks:
  - { path: "/var/vms/login.raw", size: 180 }
bridges:
  - br_ext
  - br_int
location: "{{repo_location}}"
kickstart_tempdir: "/tmp"
inventory_hostname: "login"
fqdn: "{{siteName}}.{{siteDomain}}"
networks:
  - "network --onboot=yes --bootproto=dhcp --device={{ internal_interface }} --noipv6"
  - "network --onboot={{enable_ext_nic}} --device={{external_interface}} --bootproto=static --ip={{ext_ip_addr}} --netmask={{ext_net_mask}} --nameserver={{nameserver1}} --hostname={{ fqdn }} --gateway={{ext_gateway}} --noipv6"
#  - "network --onboot={{enable_int_nic}} --device={{internal_interface}} --bootproto=static --ip={{int_ip_addr}} --netmask={{int_net_mask}} --nodefroute --noipv6"
