---

# network

external_interface: "eth0"
ext_net_addr: "86.50.166.0"
ext_ip_addr: "86.50.166.63"
ext_net_mask: "255.255.255.0"
ext_gateway: "86.50.166.1"

internal_interface: "eth1"
int_net_addr: "10.1.0.0"
int_ip_addr: "10.1.1.2"
int_net_mask: "255.255.0.0"
int_gateway: "10.1.1.4"

internal_net: "10.1.0.0/16"
internal_ip: "{{int_ip_addr}}"

network_ether_interfaces:
  - device: "{{external_interface}}"
    bootproto: "static"
    onboot: "yes"
    nm_controlled: "no"
    type: "Ethernet"

  - device: "{{internal_interface}}"
    bootproto: "static"
    onboot: "yes"
    nm_controlled: "no"
    type: "Ethernet"

network_bridge_interfaces:
  - device: "br_ext"
    type: "Bridge"
    bootproto: "static"
    onboot: "yes"
    #stp: "on"
    address: "{{ext_ip_addr}}"
    netmask: "{{ext_net_mask}}"
    gateway: "{{ext_gateway}}"
    ports: ["{{external_interface}}"]
    nm_controlled: "no"
    route:
      - network: "{{ext_net_addr}}"
        netmask: "{{ext_net_mask}}"
        gateway: "{{ext_gateway}}"

  - device: "br_int"
    type: "Bridge"
    bootproto: "static"
    onboot: "yes"
    #stp: "on"
    address: "{{int_ip_addr}}"
    netmask: "{{int_net_mask}}"
    ports: ["{{internal_interface}}"]
    nm_controlled: "no"


# Kickstart file specifics

vcpus: "{{vm_cpus}}"
ram: "{{vm_mem}}"

disks:
  - { path: "/var/vms/install.raw", size: 200 }
bridges:
  - br_ext
  - br_int
location: "{{repo_location}}"
kickstart_tempdir: "/tmp"
inventory_hostname: "install"
fqdn: "{{siteName}}-install.{{siteDomain}}"
networks:
  - "network --onboot={{enable_ext_nic}} --device={{external_interface}} --bootproto=static --ip={{ext_ip_addr}} --netmask={{ext_net_mask}} --nameserver={{nameserver1}} --hostname={{ fqdn }} --gateway={{ext_gateway}} --noipv6"
#  - "network --onboot={{enable_int_nic}} --device={{internal_interface}} --bootproto=static --ip={{int_ip_addr}} --netmask={{int_net_mask}} --nodefroute --noipv6"
